quiet: False
disable-version-string: True
with-expecter: True
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceName | lower}}_mock.go"
outpkg: mocks
packages:
  github.com/hcsouza/fiap-tech-fast-food/src/common/interfaces:
    config:
      dir: "test/mocks"
      mockname: "Mock{{.InterfaceName}}"
    interfaces:
      CustomerGateway:
      CustomerUseCase:
      CheckoutUseCase:
      DataSource:
      OrderGateway:
      OrderUseCase:
      ProductGateway:
      ProductUseCase:

