apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: db
spec:
  containers:
    - name: mongo
      image: mongo:latest
      ports:
        - containerPort: 27017
      volumeMounts:
        - mountPath: /data/db
          name: db-pv
  volumes:
    - name: db-pv
      persistentVolumeClaim:
        claimName: db-pvc
  restartPolicy: Always
