apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    name: db-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 100Mi
  hostPath:
    path: /data/db
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem